#!/usr/bin/env node

const { handleCliCommands } = require('./src/cli.js')

if (process.versions.hasOwnProperty('electron')) {
  // We're running in Electron, let the app continue normally
  require('./src/main/index.js')
} else {
  // We're in CLI or GUI launch mode
  handleCliCommands(process.argv)
}
